### ISSUE TITLE
using read() to slurp whole files as shown in perlfaq5

### ISSUE THREAD

**Issue by farblos** [perl-doc-cats/perlfaq#96]
Re-post from https://github.com/Perl/perl5/issues/18769#issue-877451881

**Where**
https://github.com/perl-doc-cats/perlfaq/blob/master/lib/perlfaq5.pod#how-can-i-read-in-an-entire-file-all-at-once--

**Description**
perlfaq5 recommends

```
read( $fh, $var, -s $fh );
```

as an option to read a whole file at once. Maybe I didn't get this right, but:

1. That function reads characters (unless binmode got requested), but the -s operators returns size in bytes, doesn't it? Usually, (size in bytes) >= (size in characters), but it anyway seems fishy to mix up these here.
2. I haven't found any guarantees in fread(3), read(3) (checked on GNU/Linux), or in Perl's implementation of the read function that read() even for binary files always will return the number of requested bytes. In other words, it seems possible that the above call slurps in a file only partially without actually failing, that is, without returning an undefined value.

Not sure whether and how these concerns/issues should be mentioned ...

Thanks for maintaining the Perl FAQ!

**Comment by Grinnz** [comment]
By default, Perl does not apply any translation layer to bytes, so they are effectively interpreted as native single-byte characters. However, on Windows there is a CRLF to LF translation layer by default, so this could also cause a mismatch.

Your second point is accurate, to slurp with `read` you need to wrap it in a while loop to read until EOF.

I think due to these issues, we should really not recommend `read` at all for slurping; the readline idiom is well-known and sufficient.

**Comment by farblos** [comment]
Thanks for caring that quickly!
